sonar.projectKey=lumia-backend
sonar.projectName=Lumia Backend
sonar.sourceEncoding=UTF-8

sonar.sources=Auther_M2/Auther_M/auth,catalog_services/app,checkout_system/app,ecommerce_cart/app,Inventory_services/app,notification_service/app,order_services/app,payment_app/app,review_services/app,support_service/app,user_profile_service/app
sonar.tests=user_profile_service/app/tests

sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/**,**/.env,**/.env.*,**/static/**,**/templates/**
sonar.coverage.exclusions=**/seed.py,**/setup*.py,**/run*.py
sonar.test.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**

sonar.python.version=3.11
