class NotificationType:
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_SHIPPED = "ORDER_SHIPPED"
    ORDER_DELIVERED = "ORDER_DELIVERED"
    SUPPORT_RESPONSE = "SUPPORT_RESPONSE"
    MARKETING = "MARKETING"